### ISSUE TITLE
Restore selections from phantoms

### ISSUE THREAD

**Issue by JJK96** [alexherbo2/phantom.kak#1]
Currently there is no way to go from phantoms back to selections.

I propose using <kbd>space</kbd> for this.

Currently when pressing <kbd>space</kbd> first the normal selection are cleared, and then when <kbd>space</kbd> is pressed again the phantoms are cleared.
I propose that pressing <kbd>space</kbd> once would transform all phantoms back to selections and then pressing <kbd>space</kbd> again would clear the selections to keep the main one (as is the default behaviour without this plugin).

**Comment by alexherbo2** [comment]
“Restore selections from phantoms” is <kbd>(</kbd> / <kbd>)</kbd>, no?

**Comment by JJK96** [comment]
Oh right, I didn't read well enough
